logging:
  level:
#    root: debug
    jdbc:
      sqltiming: info
      resultsettable: info
      sqlonly: fatal
      audit: fatal
      resultset: fatal
      connection: fatal
    org:
      springframework:
        mail: debug
        orm:
          jpa: debug

log4jdbc:
  dump.sql:
    addsemicolon: true
    maxlinelength: 0
  trim.sql:
    extrablanklines: false

spring:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy